name: Publish Gitbook
on:
  push:
    branches:
      - en
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: tuliren/publish-gitbook@v1.0.0
        with:
          # Github token for the repo
          github_token: 
